### ISSUE TITLE
App crashes shortly after execution due to NullPointerExecption

### ISSUE THREAD

**Issue by DramaticPond** [Nyabsi/VRCAA#70]
Pretty frequently, when I start the App, it crashes with the following error:

```
java.lang.NullPointerException: Parameter specified as non-null is null: method cc.sovellus.vrcaa.manager.CacheManager.addRecent, parameter world
	at cc.sovellus.vrcaa.manager.CacheManager.addRecent(Unknown Source:2)
	at cc.sovellus.vrcaa.service.PipelineService$ServiceHandler.handleMessage(PipelineService.kt:242)
	at android.os.Handler.dispatchMessage([Handler.java:107](http://handler.java:107/))
	at android.os.Looper.loopOnce([Looper.java:232](http://looper.java:232/))
	at android.os.Looper.loop([Looper.java:317](http://looper.java:317/))
	at [android.os.HandlerThread.run](http://android.os.handlerthread.run/)([HandlerThread.java:85](http://handlerthread.java:85/))
```

Android Version: 15
VRCAA Version: 2.1.0

_Aside from that, I really like the app. Thank you for your work!_

**Comment by Nyabsi** [comment]
Hello,

thanks for your report, this has happened to me few times personally as well but I didn't think too much of it.

Since it clearly is just not an issue with me, I've made an change at https://github.com/Nyabsi/VRCAA/commit/a1117df6da89002ee9f2a639af415d290b0315f3

Which is an potential fix, I will be monitoring the situation, so please do test the new build, please do let me know if it happens again within 24 hours, if not we can probably assure the bug has been fixed.

You can get the nightly release by pressing [this](https://github.com/Nyabsi/VRCAA/releases/download/nightly/VRCAA-signed.apk)

Thank you for being interested in the project.

**Comment by DramaticPond** [comment]
Thanks for the quick fix. The commit seems to have fixed the issue.

On a probably unrelated note, I get the following stack trace while logging in like described below.
Not sure if this is worth it's own issue (doesn't seem like a regression, but what do I know), but here's the steps to reproduce it.


1. Start app and login with correct email and password
2. When the TOTP screen appears, close the app
3. Start the app again, email and password are autofilled
4. When I press login, I get the error above (no TOTP dialog ever appears the second time)

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get([Collections.java:5260](http://collections.java:5260/))
	at cc.sovellus.vrcaa.api.vrchat.VRChatApi.getToken(VRChatApi.kt:139)
	at cc.sovellus.vrcaa.api.vrchat.VRChatApi$getToken$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback([Handler.java:959](http://handler.java:959/))
	at android.os.Handler.dispatchMessage([Handler.java:100](http://handler.java:100/))
	at android.os.Looper.loopOnce([Looper.java:232](http://looper.java:232/))
	at android.os.Looper.loop([Looper.java:317](http://looper.java:317/))
	at android.app.ActivityThread.main([ActivityThread.java:8744](http://activitythread.java:8744/))
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:580](http://runtimeinit.java:580/))
	at com.android.internal.os.ExecInit.main([ExecInit.java:50](http://execinit.java:50/))
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main([RuntimeInit.java:369](http://runtimeinit.java:369/))
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(eebrsl:cc.sovellus.vrcaa.ui.screen.home.HomeScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@7fd4e3a, Dispatchers.Main.immediate]
```

**Comment by Nyabsi** [comment]
should be fixed with https://github.com/Nyabsi/VRCAA/commit/215fef29501d401acfab1011e0c3edb03365750a

**Comment by Nyabsi** [comment]
I assume it has been fixed, feel free to raise the issue again if anything unexpected arises, preferably in a new issue.
